[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"
  included_files = ["server/**"]


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
from = "/api/ping"
to = "/.netlify/functions/ping"
status = 200


[[redirects]]
from = "/api/demo"
to = "/.netlify/functions/demo"
status = 200