[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"
  included_files = ["server/**"]


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
